yarnPath: .yarn/releases/yarn-3.6.3.cjs

packageExtensions:
  "local-pkg@*":
    dependencies:
      "happy-dom": "^12.5.0"
  "swiper@*":
    dependencies:
      "react": "^18.0.2"
  "@aws-sdk/core@*":
    dependencies:
      "tslib": "*"
